#!/bin/sh

#!/usr/bin/env bash

# List of capital cities
countries=(
  "Berlin"
  "Germany"
  "Amsterdam"
  "Netherlands"
  "Helsinki"
  "Finland"
  "Stockholm"
  "Sweden"
  "Copenhagen"
  "Denmark"
  "Oslo"
  "Norway"
  "Tallinn"
  "Estonia"
  "Dublin"
  "Ireland"
  "London"
  "United Kingdom"
  "Lisbon"
  "Portugal"
  "Madrid"
  "Spain"
  "Warsaw"
  "Poland"
  "Prague"
  "Czech Republic"
  "Vilnius"
  "Lithuania"
  "Wellington"
  "New Zealand"
  "Ottawa"
  "Canada"
  "Buenos Aires"
  "Argentina"
  "Brasília"
  "Brazil"
  "Santiago"
  "Chile"
  "Lima"
  "Peru"
  "Bogotá"
  "Colombia"
  "Quito"
  "Ecuador"
  "Caracas"
  "Venezuela"
  "Mexico City"
  "Mexico"
  "Ankara"
  "Turkey"
  "Baghdad"
  "Iraq"
  "Riyadh"
  "Saudi Arabia"
  "Abu Dhabi"
  "United Arab Emirates"
  "Doha"
  "Qatar"
  "Muscat"
  "Oman"
  "Kuwait City"
  "Kuwait"
  "Manama"
  "Bahrain"
  "Amman"
  "Jordan"
  "Damascus"
  "Syria"
  "Beirut"
  "Lebanon"
  "Cairo"
  "Egypt"
  "Pretoria"
  "South Africa"
  "Nairobi"
  "Kenya"
  "Addis Ababa"
  "Ethiopia"
  "Lagos"
  "Nigeria"
  "Accra"
  "Ghana"
  "Dakar"
  "Senegal"
  "Algiers"
  "Algeria"
  "Tunis"
  "Tunisia"
  "Rabat"
  "Morocco"
  "Tripoli"
  "Libya"
  "Khartoum"
  "Sudan"
  "Kinshasa"
  "DR Congo"
  "Kampala"
  "Uganda"
  "Maputo"
  "Mozambique"
  "Dar es Salaam"
  "Tanzania"
  "New Delhi"
  "India"
  "Islamabad"
  "Pakistan"
  "Kabul"
  "Afghanistan"
  "Dhaka"
  "Bangladesh"
  "Kathmandu"
  "Nepal"
  "Colombo"
  "Sri Lanka"
  "Male"
  "Maldives"
  "Beijing"
  "China"
  "Tokyo"
  "Japan"
  "Seoul"
  "South Korea"
  "Hanoi"
  "Vietnam"
  "Bangkok"
  "Thailand"
  "Jakarta"
  "Indonesia"
  "Kuala Lumpur"
  "Malaysia"
  "Singapore"
  "Singapore"
  "Manila"
  "Philippines"
  "Vientiane"
  "Laos"
  "Phnom Penh"
  "Cambodia"
  "Naypyidaw"
  "Myanmar"
  "Ulaanbaatar"
  "Mongolia"
  "Astana"
  "Kazakhstan"
  "Tashkent"
  "Uzbekistan"
  "Ashgabat"
  "Turkmenistan"
  "Bishkek"
  "Kyrgyzstan"
  "Dushanbe"
  "Tajikistan"
  "Moscow"
  "Russia"
)

# Proxy list
proxies=(
  localhost
)

# Build proxies args
proxy_args=()
for proxy in "${proxies[@]}"; do
  proxy_args+=(--proxies "$proxy")
done

# Create unified output directory
mkdir -p job_results

# Loop through countries
for country in "${countries[@]}"; do
  echo ">>> Running jobsparser for $country..."

  jobsparser --search-term '"Golang Developer" OR "Go Developer" OR "Backend Golang Developer" OR "Backend Engineer Go" OR "Software Engineer Go"' \
    --location "$country" \
    --site linkedin \
    --results-wanted 300 \
    --distance 50 \
    --job-type fulltime \
    --fetch-description \
    --hours-old 72 \
    --max-retries 0 \
    --output-dir "job_results" \
    "${proxy_args[@]}"
done